export enum Status {
  OK = 'OK',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CREATED = 'CREATED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
